config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/overview'

  get 'dashboard/loaderoptimisation'

  get 'dashboard/goldtracking'

  get 'dashboard/assetmetrics'

  resources :goldtrucks do
    collection { post :import }
  end

  resources :goldmeasures do
    collection { post :import }
  end

  resources :goldpercs do
    collection { post :import }
  end

  resources :goldpis do
    collection { post :import }
  end

  resources :truckmetrics do
    collection { post :import }
  end

  resources :opttrucks do
    collection { post :import }
  end

  resources :optloaders do
    collection { post :import }
  end

  resources :processtrucks do
    collection { post :import }
  end

  resources :loader_statuses do
    collection { post :import }
  end

  resources :opt1s do
    collection { post :import }
  end

  resources :trucks do
    collection { post :import }
  end
  

  root to: 'dashboard#overview'

end

app/models/goldtruck.rb
class Goldtruck < ActiveRecord::Base

	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |truck|
	      csv << truck.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			trucks = find_by_id(row["id"]) || new
			trucks.attributes = row.to_hash.slice!("id", "created_at", "updated_at")
			trucks.save!
		end
	end
end

app/controllers/goldtrucks_controller.rb
class GoldtrucksController < ApplicationController
  before_action :set_goldtruck, only: [:show, :edit, :update, :destroy]


  def import
    Goldtruck.import(params[:file])
    redirect_to goldtrucks_path, notice: "Products imported."
  end

  # GET /goldtrucks
  # GET /goldtrucks.json
  def index
    @goldtrucks = Goldtruck.all

    respond_to do |format|
      format.html 
      format.json
      format.csv { send_data @goldtrucks.to_csv }

    end
  end

  # GET /goldtrucks/1
  # GET /goldtrucks/1.json
  def show
  end

  # GET /goldtrucks/new
  def new
    @goldtruck = Goldtruck.new
  end

  # GET /goldtrucks/1/edit
  def edit
  end

  # POST /goldtrucks
  # POST /goldtrucks.json
  def create
    @goldtruck = Goldtruck.new(goldtruck_params)

    respond_to do |format|
      if @goldtruck.save
        format.html { redirect_to @goldtruck, notice: 'Goldtruck was successfully created.' }
        format.json { render :show, status: :created, location: @goldtruck }
      else
        format.html { render :new }
        format.json { render json: @goldtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goldtrucks/1
  # PATCH/PUT /goldtrucks/1.json
  def update
    respond_to do |format|
      if @goldtruck.update(goldtruck_params)
        format.html { redirect_to @goldtruck, notice: 'Goldtruck was successfully updated.' }
        format.json { render :show, status: :ok, location: @goldtruck }
      else
        format.html { render :edit }
        format.json { render json: @goldtruck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goldtrucks/1
  # DELETE /goldtrucks/1.json
  def destroy
    @goldtruck.destroy
    respond_to do |format|
      format.html { redirect_to goldtrucks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goldtruck
      @goldtruck = Goldtruck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goldtruck_params
      params.require(:goldtruck).permit(:time, :t1, :t2, :t3, :t4, :t5, :t6, :t7, :t8, :t9, :t10, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24, :t25)
    end
end

app/helpers/goldtrucks_helper.rb
module GoldtrucksHelper
end

app/views/goldtrucks/_form.html.erb
<%= form_for(@goldtruck) do |f| %>
  <% if @goldtruck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goldtruck.errors.count, "error") %> prohibited this goldtruck from being saved:</h2>

      <ul>
      <% @goldtruck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :t1 %><br>
    <%= f.text_field :t1 %>
  </div>
  <div class="field">
    <%= f.label :t2 %><br>
    <%= f.text_field :t2 %>
  </div>
  <div class="field">
    <%= f.label :t3 %><br>
    <%= f.text_field :t3 %>
  </div>
  <div class="field">
    <%= f.label :t4 %><br>
    <%= f.text_field :t4 %>
  </div>
  <div class="field">
    <%= f.label :t5 %><br>
    <%= f.text_field :t5 %>
  </div>
  <div class="field">
    <%= f.label :t6 %><br>
    <%= f.text_field :t6 %>
  </div>
  <div class="field">
    <%= f.label :t7 %><br>
    <%= f.text_field :t7 %>
  </div>
  <div class="field">
    <%= f.label :t8 %><br>
    <%= f.text_field :t8 %>
  </div>
  <div class="field">
    <%= f.label :t9 %><br>
    <%= f.text_field :t9 %>
  </div>
  <div class="field">
    <%= f.label :t10 %><br>
    <%= f.text_field :t10 %>
  </div>
  <div class="field">
    <%= f.label :t11 %><br>
    <%= f.text_field :t11 %>
  </div>
  <div class="field">
    <%= f.label :t12 %><br>
    <%= f.text_field :t12 %>
  </div>
  <div class="field">
    <%= f.label :t13 %><br>
    <%= f.text_field :t13 %>
  </div>
  <div class="field">
    <%= f.label :t14 %><br>
    <%= f.text_field :t14 %>
  </div>
  <div class="field">
    <%= f.label :t15 %><br>
    <%= f.text_field :t15 %>
  </div>
  <div class="field">
    <%= f.label :t16 %><br>
    <%= f.text_field :t16 %>
  </div>
  <div class="field">
    <%= f.label :t17 %><br>
    <%= f.text_field :t17 %>
  </div>
  <div class="field">
    <%= f.label :t18 %><br>
    <%= f.text_field :t18 %>
  </div>
  <div class="field">
    <%= f.label :t19 %><br>
    <%= f.text_field :t19 %>
  </div>
  <div class="field">
    <%= f.label :t20 %><br>
    <%= f.text_field :t20 %>
  </div>
  <div class="field">
    <%= f.label :t21 %><br>
    <%= f.text_field :t21 %>
  </div>
  <div class="field">
    <%= f.label :t22 %><br>
    <%= f.text_field :t22 %>
  </div>
  <div class="field">
    <%= f.label :t23 %><br>
    <%= f.text_field :t23 %>
  </div>
  <div class="field">
    <%= f.label :t24 %><br>
    <%= f.text_field :t24 %>
  </div>
  <div class="field">
    <%= f.label :t25 %><br>
    <%= f.text_field :t25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goldtrucks/edit.html.erb
<h1>Editing goldtruck</h1>

<%= render 'form' %>

<%= link_to 'Show', @goldtruck %> |
<%= link_to 'Back', goldtrucks_path %>

app/views/goldtrucks/index.html.erb
<h1>Listing goldtrucks</h1>

<p>
  <b>Download:</b>
  <%= link_to "CSV", goldtrucks_path(format: "csv") %>
</p>

  <b>Upload:</b>
<%= form_tag import_goldtrucks_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<%= form_tag("/goldtrucks", method: "get") do %>
  <%= label_tag(:datetimestamp, "Specify Time:") %>
  <%= text_field_tag(:datetimestamp) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>T1</th>
      <th>T2</th>
      <th>T3</th>
      <th>T4</th>
      <th>T5</th>
      <th>T6</th>
      <th>T7</th>
      <th>T8</th>
      <th>T9</th>
      <th>T10</th>
      <th>T11</th>
      <th>T12</th>
      <th>T13</th>
      <th>T14</th>
      <th>T15</th>
      <th>T16</th>
      <th>T17</th>
      <th>T18</th>
      <th>T19</th>
      <th>T20</th>
      <th>T21</th>
      <th>T22</th>
      <th>T23</th>
      <th>T24</th>
      <th>T25</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goldtrucks.each do |goldtruck| %>
      <tr>
        <td><%= goldtruck.time %></td>
        <td><%= goldtruck.t1 %></td>
        <td><%= goldtruck.t2 %></td>
        <td><%= goldtruck.t3 %></td>
        <td><%= goldtruck.t4 %></td>
        <td><%= goldtruck.t5 %></td>
        <td><%= goldtruck.t6 %></td>
        <td><%= goldtruck.t7 %></td>
        <td><%= goldtruck.t8 %></td>
        <td><%= goldtruck.t9 %></td>
        <td><%= goldtruck.t10 %></td>
        <td><%= goldtruck.t11 %></td>
        <td><%= goldtruck.t12 %></td>
        <td><%= goldtruck.t13 %></td>
        <td><%= goldtruck.t14 %></td>
        <td><%= goldtruck.t15 %></td>
        <td><%= goldtruck.t16 %></td>
        <td><%= goldtruck.t17 %></td>
        <td><%= goldtruck.t18 %></td>
        <td><%= goldtruck.t19 %></td>
        <td><%= goldtruck.t20 %></td>
        <td><%= goldtruck.t21 %></td>
        <td><%= goldtruck.t22 %></td>
        <td><%= goldtruck.t23 %></td>
        <td><%= goldtruck.t24 %></td>
        <td><%= goldtruck.t25 %></td>
        <td><%= link_to 'Show', goldtruck %></td>
        <td><%= link_to 'Edit', edit_goldtruck_path(goldtruck) %></td>
        <td><%= link_to 'Destroy', goldtruck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goldtruck', new_goldtruck_path %>

app/views/goldtrucks/new.html.erb
<h1>New goldtruck</h1>

<%= render 'form' %>

<%= link_to 'Back', goldtrucks_path %>

app/views/goldtrucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @goldtruck.time %>
</p>

<p>
  <strong>T1:</strong>
  <%= @goldtruck.t1 %>
</p>

<p>
  <strong>T2:</strong>
  <%= @goldtruck.t2 %>
</p>

<p>
  <strong>T3:</strong>
  <%= @goldtruck.t3 %>
</p>

<p>
  <strong>T4:</strong>
  <%= @goldtruck.t4 %>
</p>

<p>
  <strong>T5:</strong>
  <%= @goldtruck.t5 %>
</p>

<p>
  <strong>T6:</strong>
  <%= @goldtruck.t6 %>
</p>

<p>
  <strong>T7:</strong>
  <%= @goldtruck.t7 %>
</p>

<p>
  <strong>T8:</strong>
  <%= @goldtruck.t8 %>
</p>

<p>
  <strong>T9:</strong>
  <%= @goldtruck.t9 %>
</p>

<p>
  <strong>T10:</strong>
  <%= @goldtruck.t10 %>
</p>

<p>
  <strong>T11:</strong>
  <%= @goldtruck.t11 %>
</p>

<p>
  <strong>T12:</strong>
  <%= @goldtruck.t12 %>
</p>

<p>
  <strong>T13:</strong>
  <%= @goldtruck.t13 %>
</p>

<p>
  <strong>T14:</strong>
  <%= @goldtruck.t14 %>
</p>

<p>
  <strong>T15:</strong>
  <%= @goldtruck.t15 %>
</p>

<p>
  <strong>T16:</strong>
  <%= @goldtruck.t16 %>
</p>

<p>
  <strong>T17:</strong>
  <%= @goldtruck.t17 %>
</p>

<p>
  <strong>T18:</strong>
  <%= @goldtruck.t18 %>
</p>

<p>
  <strong>T19:</strong>
  <%= @goldtruck.t19 %>
</p>

<p>
  <strong>T20:</strong>
  <%= @goldtruck.t20 %>
</p>

<p>
  <strong>T21:</strong>
  <%= @goldtruck.t21 %>
</p>

<p>
  <strong>T22:</strong>
  <%= @goldtruck.t22 %>
</p>

<p>
  <strong>T23:</strong>
  <%= @goldtruck.t23 %>
</p>

<p>
  <strong>T24:</strong>
  <%= @goldtruck.t24 %>
</p>

<p>
  <strong>T25:</strong>
  <%= @goldtruck.t25 %>
</p>

<%= link_to 'Edit', edit_goldtruck_path(@goldtruck) %> |
<%= link_to 'Back', goldtrucks_path %>