config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/overview'

  get 'dashboard/loaderoptimisation'

  get 'dashboard/goldtracking'

  get 'dashboard/assetmetrics'

  resources :goldtrucks do
    collection { post :import }
  end

  resources :goldmeasures do
    collection { post :import }
  end

  resources :goldpercs do
    collection { post :import }
  end

  resources :goldpis do
    collection { post :import }
  end

  resources :truckmetrics do
    collection { post :import }
  end

  resources :opttrucks do
    collection { post :import }
  end

  resources :optloaders do
    collection { post :import }
  end

  resources :processtrucks do
    collection { post :import }
  end

  resources :loader_statuses do
    collection { post :import }
  end

  resources :opt1s do
    collection { post :import }
  end

  resources :trucks do
    collection { post :import }
  end
  

  root to: 'dashboard#overview'

end

app/models/goldperc.rb
class Goldperc < ActiveRecord::Base
		def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |truck|
	      csv << truck.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			trucks = find_by_id(row["id"]) || new
			trucks.attributes = row.to_hash.slice!("id", "created_at", "updated_at")
			trucks.save!
		end
	end
end

app/controllers/goldpercs_controller.rb
class GoldpercsController < ApplicationController
  before_action :set_goldperc, only: [:show, :edit, :update, :destroy]

  def import
    Goldperc.import(params[:file])
    redirect_to goldpis_path, notice: "Products imported."
  end

  # GET /goldpercs
  # GET /goldpercs.json
  def index
    @goldpercs = Goldperc.all

    respond_to do |format|
      format.html 
      format.json
      format.csv { send_data @goldpercs.to_csv }

    end
  end

  # GET /goldpercs/1
  # GET /goldpercs/1.json
  def show
  end

  # GET /goldpercs/new
  def new
    @goldperc = Goldperc.new
  end

  # GET /goldpercs/1/edit
  def edit
  end

  # POST /goldpercs
  # POST /goldpercs.json
  def create
    @goldperc = Goldperc.new(goldperc_params)

    respond_to do |format|
      if @goldperc.save
        format.html { redirect_to @goldperc, notice: 'Goldperc was successfully created.' }
        format.json { render :show, status: :created, location: @goldperc }
      else
        format.html { render :new }
        format.json { render json: @goldperc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goldpercs/1
  # PATCH/PUT /goldpercs/1.json
  def update
    respond_to do |format|
      if @goldperc.update(goldperc_params)
        format.html { redirect_to @goldperc, notice: 'Goldperc was successfully updated.' }
        format.json { render :show, status: :ok, location: @goldperc }
      else
        format.html { render :edit }
        format.json { render json: @goldperc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goldpercs/1
  # DELETE /goldpercs/1.json
  def destroy
    @goldperc.destroy
    respond_to do |format|
      format.html { redirect_to goldpercs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goldperc
      @goldperc = Goldperc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goldperc_params
      params.require(:goldperc).permit(:time, :under_shtd, :above_shtd)
    end
end

app/helpers/goldpercs_helper.rb
module GoldpercsHelper
end

app/views/goldpercs/_form.html.erb
<%= form_for(@goldperc) do |f| %>
  <% if @goldperc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goldperc.errors.count, "error") %> prohibited this goldperc from being saved:</h2>

      <ul>
      <% @goldperc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :under_shtd %><br>
    <%= f.text_field :under_shtd %>
  </div>
  <div class="field">
    <%= f.label :above_shtd %><br>
    <%= f.text_field :above_shtd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goldpercs/edit.html.erb
<h1>Editing goldperc</h1>

<%= render 'form' %>

<%= link_to 'Show', @goldperc %> |
<%= link_to 'Back', goldpercs_path %>

app/views/goldpercs/index.html.erb
<h1>Listing goldpercs</h1>


<p>
  <b>Download:</b>
  <%= link_to "CSV", goldpercs_path(format: "csv") %>
</p>

  <b>Upload:</b>
<%= form_tag import_goldpercs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<%= form_tag("/goldpercs", method: "get") do %>
  <%= label_tag(:datetimestamp, "Specify Time:") %>
  <%= text_field_tag(:datetimestamp) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Under shtd</th>
      <th>Above shtd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goldpercs.each do |goldperc| %>
      <tr>
        <td><%= goldperc.time %></td>
        <td><%= goldperc.under_shtd %></td>
        <td><%= goldperc.above_shtd %></td>
        <td><%= link_to 'Show', goldperc %></td>
        <td><%= link_to 'Edit', edit_goldperc_path(goldperc) %></td>
        <td><%= link_to 'Destroy', goldperc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goldperc', new_goldperc_path %>

app/views/goldpercs/new.html.erb
<h1>New goldperc</h1>

<%= render 'form' %>

<%= link_to 'Back', goldpercs_path %>

app/views/goldpercs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @goldperc.time %>
</p>

<p>
  <strong>Under shtd:</strong>
  <%= @goldperc.under_shtd %>
</p>

<p>
  <strong>Above shtd:</strong>
  <%= @goldperc.above_shtd %>
</p>

<%= link_to 'Edit', edit_goldperc_path(@goldperc) %> |
<%= link_to 'Back', goldpercs_path %>