config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/overview'

  get 'dashboard/loaderoptimisation'

  get 'dashboard/goldtracking'

  get 'dashboard/assetmetrics'

  resources :goldtrucks do
    collection { post :import }
  end

  resources :goldmeasures do
    collection { post :import }
  end

  resources :goldpercs do
    collection { post :import }
  end

  resources :goldpis do
    collection { post :import }
  end

  resources :truckmetrics do
    collection { post :import }
  end

  resources :opttrucks do
    collection { post :import }
  end

  resources :optloaders do
    collection { post :import }
  end

  resources :processtrucks do
    collection { post :import }
  end

  resources :loader_statuses do
    collection { post :import }
  end

  resources :opt1s do
    collection { post :import }
  end

  resources :trucks do
    collection { post :import }
  end
  

  root to: 'dashboard#overview'

end

app/models/goldmeasure.rb
class Goldmeasure < ActiveRecord::Base
	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |truck|
	      csv << truck.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			trucks = find_by_id(row["id"]) || new
			trucks.attributes = row.to_hash.slice!("id", "created_at", "updated_at")
			trucks.save!
		end
	end
end

app/controllers/goldmeasures_controller.rb
class GoldmeasuresController < ApplicationController
  before_action :set_goldmeasure, only: [:show, :edit, :update, :destroy]

  def import
    Goldmeasure.import(params[:file])
    redirect_to goldmeasures_path, notice: "Products imported."
  end

  # GET /goldmeasures
  # GET /goldmeasures.json
  def index
    @goldmeasures = Goldmeasure.all

    respond_to do |format|
      format.html 
      format.json
      format.csv { send_data @goldmeasures.to_csv }

    end
  end

  # GET /goldmeasures/1
  # GET /goldmeasures/1.json
  def show
  end

  # GET /goldmeasures/new
  def new
    @goldmeasure = Goldmeasure.new
  end

  # GET /goldmeasures/1/edit
  def edit
  end

  # POST /goldmeasures
  # POST /goldmeasures.json
  def create
    @goldmeasure = Goldmeasure.new(goldmeasure_params)

    respond_to do |format|
      if @goldmeasure.save
        format.html { redirect_to @goldmeasure, notice: 'Goldmeasure was successfully created.' }
        format.json { render :show, status: :created, location: @goldmeasure }
      else
        format.html { render :new }
        format.json { render json: @goldmeasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goldmeasures/1
  # PATCH/PUT /goldmeasures/1.json
  def update
    respond_to do |format|
      if @goldmeasure.update(goldmeasure_params)
        format.html { redirect_to @goldmeasure, notice: 'Goldmeasure was successfully updated.' }
        format.json { render :show, status: :ok, location: @goldmeasure }
      else
        format.html { render :edit }
        format.json { render json: @goldmeasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goldmeasures/1
  # DELETE /goldmeasures/1.json
  def destroy
    @goldmeasure.destroy
    respond_to do |format|
      format.html { redirect_to goldmeasures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goldmeasure
      @goldmeasure = Goldmeasure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goldmeasure_params
      params.require(:goldmeasure).permit(:time, :total_shtd)
    end
end

app/helpers/goldmeasures_helper.rb
module GoldmeasuresHelper
end

app/views/goldmeasures/_form.html.erb
<%= form_for(@goldmeasure) do |f| %>
  <% if @goldmeasure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goldmeasure.errors.count, "error") %> prohibited this goldmeasure from being saved:</h2>

      <ul>
      <% @goldmeasure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :total_shtd %><br>
    <%= f.text_field :total_shtd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goldmeasures/edit.html.erb
<h1>Editing goldmeasure</h1>

<%= render 'form' %>

<%= link_to 'Show', @goldmeasure %> |
<%= link_to 'Back', goldmeasures_path %>

app/views/goldmeasures/index.html.erb
<h1>Listing goldmeasures</h1>

<p>
  <b>Download:</b>
  <%= link_to "CSV", goldmeasures_path(format: "csv") %>
</p>

  <b>Upload:</b>
<%= form_tag import_goldmeasures_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<%= form_tag("/goldmeasures", method: "get") do %>
  <%= label_tag(:datetimestamp, "Specify Time:") %>
  <%= text_field_tag(:datetimestamp) %>
  <%= submit_tag("Search") %>
<% end %>

<br>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Total shtd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goldmeasures.each do |goldmeasure| %>
      <tr>
        <td><%= goldmeasure.time %></td>
        <td><%= goldmeasure.total_shtd %></td>
        <td><%= link_to 'Show', goldmeasure %></td>
        <td><%= link_to 'Edit', edit_goldmeasure_path(goldmeasure) %></td>
        <td><%= link_to 'Destroy', goldmeasure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goldmeasure', new_goldmeasure_path %>

app/views/goldmeasures/new.html.erb
<h1>New goldmeasure</h1>

<%= render 'form' %>

<%= link_to 'Back', goldmeasures_path %>

app/views/goldmeasures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @goldmeasure.time %>
</p>

<p>
  <strong>Total shtd:</strong>
  <%= @goldmeasure.total_shtd %>
</p>

<%= link_to 'Edit', edit_goldmeasure_path(@goldmeasure) %> |
<%= link_to 'Back', goldmeasures_path %>