config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/overview'

  get 'dashboard/loaderoptimisation'

  get 'dashboard/goldtracking'

  get 'dashboard/assetmetrics'

  resources :goldtrucks do
    collection { post :import }
  end

  resources :goldmeasures do
    collection { post :import }
  end

  resources :goldpercs do
    collection { post :import }
  end

  resources :goldpis do
    collection { post :import }
  end

  resources :truckmetrics do
    collection { post :import }
  end

  resources :opttrucks do
    collection { post :import }
  end

  resources :optloaders do
    collection { post :import }
  end

  resources :processtrucks do
    collection { post :import }
  end

  resources :loader_statuses do
    collection { post :import }
  end

  resources :opt1s do
    collection { post :import }
  end

  resources :trucks do
    collection { post :import }
  end
  

  root to: 'dashboard#overview'

end

app/views/layouts/_navigation.html.erb
    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"><%= image_tag("logo.png", width: "20", height: "20") %> Optimines</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li> <%# class="active" %>
            <%= link_to "Overview", dashboard_overview_path %>
          </li>
          <li>
            <%= link_to "Loader Optimisation", dashboard_loaderoptimisation_path %>
          </li>
          <li>
            <%= link_to "Gold Tracking", dashboard_goldtracking_path %>
          </li>
          <li>
            <%= link_to "Asset Metrics", dashboard_assetmetrics_path %>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Optimines</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
<%# For Debugging %>

<%= render 'layouts/navigation' %>

<% if Rails.env == "development" %>
   <%= params %>
   <br>
   <%= session %>
   <hr>
    <%= link_to "Opt1s", opt1s_path %>
    <%= link_to "Opt Loader", optloaders_path %>
    <%= link_to "Opt Trucks", opttrucks_path %>
    <%= link_to "Truck Metrics", truckmetrics_path %>
    <%= link_to "Gold Pi", goldpis_path %>
    <%= link_to "Gold Percentage", goldpercs_path %>
    <%= link_to "Gold Measures", goldmeasures_path %>
    <%= link_to "Gold Trucks", goldtrucks_path %>
<% end %>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>


<%= yield %>

<%# = link_to "Trucks", trucks_path %>
<%# = link_to "Loader Statuses", loader_statuses_path %>
<%# = link_to "Process Trucks", processtrucks_path %>

</div>



	


</body>


</html>